### ISSUE TITLE
I can't differentiate what is source code , products code and demo?

### ISSUE THREAD

**Issue by luolawlan** [Siyu1017/StyleViewer.js#2]
I can't differentiate what is source code , products code and demo.
What are the contribution guide ?

**Comment by Siyu1017** [comment]
> I can't differentiate what is source code , products code and demo. What are the contribution guide ?

針對您所說的問題，我將檔案重新做了整理，源代碼在 `src/StyleViewer.js`，產品代碼在 `dist/StyleViewer.min.js`，演示則在 https://siyu1017.github.io/StyleViewer.js/

**Comment by luolawlan** [comment]
Thanks.
